In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns

In [2]:
psi = pd.read_csv('GTEx.psi.tsv.gz', sep='\t')
cluster_counts = pd.read_csv('GTEx.cluster_counts.tsv.gz', sep='\t')
psi_p = pd.read_csv('GTEx.psi_pvals.tsv.gz', sep='\t')

In [3]:
ten_tissues =['Brain-Anteriorcingulatecortex_BA24',
 'Brain-Cortex',
 'Brain-FrontalCortex_BA9',
 'Brain-Putamen_basalganglia',
 'Heart-AtrialAppendage',
 'Liver',
 'Lung',
 'Muscle-Skeletal',
 'Skin-NotSunExposed_Suprapubic',
 'WholeBlood']

In [4]:
psi['intron_cluster'] = psi.intron + ':' + psi.cluster + psi.gene_id#.loc[]#[ten_tissues]

In [5]:
psi = psi.loc[psi.ctype=='PR,UP'].dropna()

In [6]:
psi.index = psi.intron

In [7]:
psi.loc[(psi[ten_tissues].quantile(0.9, axis=1) >= 0.25) & (psi[ten_tissues].quantile(0.3, axis=1) <= 0.05)]

,intron,cluster,itype,ctype,gene_name,gene_id,Artery-Aorta,Brain-Cortex,Brain-Nucleusaccumbens_basalganglia,Esophagus-Muscularis,...,Cells-EBV-transformedlymphocytes,Colon-Sigmoid,Colon-Transverse,Liver,Muscle-Skeletal,Nerve-Tibial,Skin-NotSunExposed_Suprapubic,Skin-SunExposed_Lowerleg,WholeBlood,intron_cluster
intron,,,,,,,,,,,,,,,,,,,,,
chr10:11257872:11270665:clu_23019_+,chr10:11257872:11270665:clu_23019_+,chr10:clu_23019_+,UP,"PR,UP",CELF2,ENSG00000048740.18,0.084550,0.031257,0.056009,0.084819,...,0.112751,0.091103,0.127199,0.421130,3.347252e-02,0.151720,0.136804,0.124067,3.064609e-01,chr10:11257872:11270665:clu_23019_+:chr10:clu_...
chr10:12149961:12156906:clu_23029_+,chr10:12149961:12156906:clu_23029_+,chr10:clu_23029_+,UP,"PR,UP",SEC61A2,ENSG00000065665.20,0.732512,0.044404,0.044734,0.632632,...,0.339305,0.584586,0.555772,0.427668,1.017591e-01,0.639872,0.746636,0.748614,6.986313e-01,chr10:12149961:12156906:clu_23029_+:chr10:clu_...
chr10:26734723:26735239:clu_23110_+,chr10:26734723:26735239:clu_23110_+,chr10:clu_23110_+,UP,"PR,UP",PDSS1,ENSG00000148459.15,0.003621,0.391989,0.541473,0.009260,...,0.001224,0.012264,0.004446,0.094549,5.787476e-10,0.005751,0.005012,0.007823,3.975851e-08,chr10:26734723:26735239:clu_23110_+:chr10:clu_...
chr10:63599283:63599669:clu_23272_+,chr10:63599283:63599669:clu_23272_+,chr10:clu_23272_+,UP,"PR,UP",REEP3,ENSG00000165476.13,0.004346,0.224465,0.076146,0.003788,...,0.005112,0.008337,0.003146,0.000656,4.955740e-01,0.011786,0.004034,0.002816,5.175090e-03,chr10:63599283:63599669:clu_23272_+:chr10:clu_...
chr10:97164890:97185477:clu_24439_-,chr10:97164890:97185477:clu_24439_-,chr10:clu_24439_-,PR,"PR,UP",SLIT1,ENSG00000187122.16,0.018783,0.754569,0.850720,0.012257,...,0.001765,0.052119,0.041839,0.020731,7.247956e-03,0.001191,0.009751,0.006952,3.727718e-04,chr10:97164890:97185477:clu_24439_-:chr10:clu_...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
chr9:36066870:36080604:clu_21436_+,chr9:36066870:36080604:clu_21436_+,chr9:clu_21436_+,UP,"PR,UP",RECK,ENSG00000122707.11,0.008241,0.269219,0.197442,0.017164,...,0.009766,0.017524,0.010386,0.023125,9.019958e-02,0.031745,0.008382,0.010579,3.428463e-03,chr9:36066870:36080604:clu_21436_+:chr9:clu_21...
chr9:98745675:98746059:clu_22593_-,chr9:98745675:98746059:clu_22593_-,chr9:clu_22593_-,UP,"PR,UP",ANKS6,ENSG00000165138.17,0.005798,0.399121,0.233830,0.003378,...,0.012650,0.006393,0.006680,0.014334,2.043193e-01,0.009048,0.004780,0.004535,2.200428e-02,chr9:98745675:98746059:clu_22593_-:chr9:clu_22...
chr9:98746094:98751028:clu_22593_-,chr9:98746094:98751028:clu_22593_-,chr9:clu_22593_-,UP,"PR,UP",ANKS6,ENSG00000165138.17,0.005028,0.337908,0.200016,0.002825,...,0.002225,0.003559,0.002870,0.016130,1.673813e-01,0.006112,0.003891,0.002765,1.867734e-02,chr9:98746094:98751028:clu_22593_-:chr9:clu_22...
chr9:98784157:98784379:clu_22595_-,chr9:98784157:98784379:clu_22595_-,chr9:clu_22595_-,UP,"PR,UP",ANKS6,ENSG00000165138.17,0.017025,0.594956,0.282016,0.056702,...,0.033682,0.042655,0.032043,0.008439,4.858402e-01,0.018583,0.015296,0.008698,2.196439e-02,chr9:98784157:98784379:clu_22595_-:chr9:clu_22...
chrX:70492596:70495407:clu_46843_+,chrX:70492596:70495407:clu_46843_+,chrX:clu_46843_+,PR,"PR,UP",DLG3,ENSG00000082458.11,0.003601,0.315614,0.298262,0.001258,...,0.003870,0.002688,0.001988,0.021506,4.942698e-03,0.001125,0.031034,0.029081,5.678991e-02,chrX:70492596:70495407:clu_46843_+:chrX:clu_46...

In [8]:
cluster_counts.index = cluster_counts.intron
cluster_counts = cluster_counts.loc[cluster_counts.ctype=='PR,UP'].dropna()

In [9]:
cluster_counts = cluster_counts.groupby(['cluster'])[ten_tissues].sum()

In [10]:
min_per_tissue= pd.DataFrame(cluster_counts.min(axis=1))
min_per_tissue.columns = ['min_cluster_counts']

In [11]:
psi = pd.merge(psi, min_per_tissue, right_on='cluster', left_on='cluster')

In [12]:
psi

,intron,cluster,itype,ctype,gene_name,gene_id,Artery-Aorta,Brain-Cortex,Brain-Nucleusaccumbens_basalganglia,Esophagus-Muscularis,...,Colon-Sigmoid,Colon-Transverse,Liver,Muscle-Skeletal,Nerve-Tibial,Skin-NotSunExposed_Suprapubic,Skin-SunExposed_Lowerleg,WholeBlood,intron_cluster,min_cluster_counts
0,chr10:100190968:100192458:clu_24474_-,chr10:clu_24474_-,UP,"PR,UP",CHUK,ENSG00000213341.10,0.083039,0.240722,0.157675,0.087538,...,0.119784,0.063494,0.030676,2.097741e-01,0.208999,0.158868,0.165861,4.232702e-02,chr10:100190968:100192458:clu_24474_-:chr10:cl...,13.0
1,chr10:100190968:100193297:clu_24474_-,chr10:clu_24474_-,PR,"PR,UP",CHUK,ENSG00000213341.10,0.898162,0.746643,0.832342,0.897091,...,0.866662,0.920792,0.960513,7.834369e-01,0.776225,0.824149,0.823942,9.379591e-01,chr10:100190968:100193297:clu_24474_-:chr10:cl...,13.0
2,chr10:100190968:100193388:clu_24474_-,chr10:clu_24474_-,UP,"PR,UP",CHUK,ENSG00000213341.10,0.018799,0.013974,0.010515,0.015813,...,0.013979,0.015714,0.009786,7.654834e-03,0.014777,0.017519,0.010528,1.971404e-02,chr10:100190968:100193388:clu_24474_-:chr10:cl...,13.0
3,chr10:100238231:100243697:clu_24476_-,chr10:clu_24476_-,PR,"PR,UP",CWF19L1,ENSG00000095485.16,0.769964,0.734673,0.758405,0.758501,...,0.736635,0.708119,0.718045,6.605725e-01,0.768813,0.750186,0.740016,7.150701e-01,chr10:100238231:100243697:clu_24476_-:chr10:cl...,21.0
4,chr10:100238231:100253420:clu_24476_-,chr10:clu_24476_-,UP,"PR,UP",CWF19L1,ENSG00000095485.16,0.003448,0.001879,0.003567,0.000632,...,0.000845,0.001569,0.001894,9.722217e-04,0.001237,0.002044,0.001471,5.309624e-03,chr10:100238231:100253420:clu_24476_-:chr10:cl...,21.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25115,chrX:81202720:81276983:clu_46894_+,chrX:clu_46894_+,UP,"PR,UP",SH3BGRL,ENSG00000131171.12,0.001368,0.000991,0.001026,0.003878,...,0.006298,0.004419,0.016771,9.135068e-04,0.001134,0.000356,0.000680,3.025626e-03,chrX:81202720:81276983:clu_46894_+:chrX:clu_46...,23.0
25116,chrX:86027557:86047246:clu_47602_-,chrX:clu_47602_-,UP,"PR,UP",CHM,ENSG00000188419.13,0.030148,0.098507,0.209290,0.015105,...,0.014099,0.012205,0.020293,9.271741e-09,0.024093,0.003534,0.016737,7.855145e-08,chrX:86027557:86047246:clu_47602_-:chrX:clu_47...,1.0
25117,chrX:86027557:86047483:clu_47602_-,chrX:clu_47602_-,PR,"PR,UP",CHM,ENSG00000188419.13,0.969852,0.901493,0.790710,0.984895,...,0.985901,0.987795,0.979707,1.000000e+00,0.975907,0.996466,0.983263,9.999999e-01,chrX:86027557:86047483:clu_47602_-:chrX:clu_47...,1.0
25118,chrY:2854771:2865087:clu_47887_+,chrY:clu_47887_+,PR,"PR,UP",RPS4Y1,ENSG00000129824.15,0.999546,0.999505,0.999701,0.999467,...,0.999557,0.999601,0.999629,9.996583e-01,0.999478,0.999528,0.999444,9.996002e-01,chrY:2854771:2865087:clu_47887_+:chrY:clu_4788...,330.0
25119,chrY:2854771:2928863:clu_47887_+,chrY:clu_47887_+,UP,"PR,UP",RPS4Y1,ENSG00000129824.15,0.000454,0.000495,0.000299,0.000533,...,0.000443,0.000399,0.000371,3.417466e-04,0.000522,0.000472,0.000556,3.997937e-04,chrY:2854771:2928863:clu_47887_+:chrY:clu_4788...,330.0

In [13]:
exp = cluster_counts.loc[cluster_counts[ten_tissues].min(axis=1) >= 10].index

In [14]:
spli = psi.loc[(psi[ten_tissues].quantile(0.9, axis=1) >= 0.25) & (psi[ten_tissues].quantile(0.3, axis=1) <= 0.05) & (psi.min_cluster_counts >= 10) & (psi.itype=='UP')]

In [20]:
psi.loc[psi.gene_name=='MYOM2']

,intron,cluster,itype,ctype,gene_name,gene_id,Artery-Aorta,Brain-Cortex,Brain-Nucleusaccumbens_basalganglia,Esophagus-Muscularis,...,Colon-Sigmoid,Colon-Transverse,Liver,Muscle-Skeletal,Nerve-Tibial,Skin-NotSunExposed_Suprapubic,Skin-SunExposed_Lowerleg,WholeBlood,intron_cluster,min_cluster_counts
23175,chr8:2124217:2129126:clu_19481_+,chr8:clu_19481_+,PR,"PR,UP",MYOM2,ENSG00000036448.9,0.262212,0.766136,0.475583,0.715257,...,0.553576,0.499478,0.374221,0.993753,0.342728,0.507196,0.481373,0.865207,chr8:2124217:2129126:clu_19481_+:chr8:clu_1948...,5.0
23176,chr8:2127881:2129126:clu_19481_+,chr8:clu_19481_+,UP,"PR,UP",MYOM2,ENSG00000036448.9,0.737788,0.233864,0.524417,0.284743,...,0.446424,0.500522,0.625779,0.006247,0.657272,0.492804,0.518627,0.134793,chr8:2127881:2129126:clu_19481_+:chr8:clu_1948...,5.0
23177,chr8:2140886:2141140:clu_19482_+,chr8:clu_19482_+,PR,"PR,UP",MYOM2,ENSG00000036448.9,0.317844,0.308234,0.306374,0.330888,...,0.322884,0.315158,0.341469,0.335880,0.322467,0.335434,0.343428,0.337670,chr8:2140886:2141140:clu_19482_+:chr8:clu_1948...,14.0
23178,chr8:2140886:2142374:clu_19482_+,chr8:clu_19482_+,UP,"PR,UP",MYOM2,ENSG00000036448.9,0.006863,0.008382,0.004538,0.003870,...,0.006659,0.010488,0.002469,0.000725,0.006471,0.000797,0.001949,0.003321,chr8:2140886:2142374:clu_19482_+:chr8:clu_1948...,14.0
23179,chr8:2140886:2143400:clu_19482_+,chr8:clu_19482_+,PR,"PR,UP",MYOM2,ENSG00000036448.9,0.100997,0.024054,0.057600,0.013677,...,0.033161,0.102401,0.186765,0.000249,0.039397,0.124055,0.084908,0.047222,chr8:2140886:2143400:clu_19482_+:chr8:clu_1948...,14.0
23180,chr8:2141177:2142374:clu_19482_+,chr8:clu_19482_+,PR,"PR,UP",MYOM2,ENSG00000036448.9,0.300568,0.315214,0.313556,0.329337,...,0.325102,0.293109,0.241890,0.344221,0.320410,0.284444,0.293329,0.313342,chr8:2141177:2142374:clu_19482_+:chr8:clu_1948...,14.0
23181,chr8:2142397:2143400:clu_19482_+,chr8:clu_19482_+,PR,"PR,UP",MYOM2,ENSG00000036448.9,0.273729,0.344116,0.317932,0.322228,...,0.312194,0.278843,0.227408,0.318925,0.311254,0.255270,0.276385,0.298446,chr8:2142397:2143400:clu_19482_+:chr8:clu_1948...,14.0

In [16]:
psi.loc[psi.cluster=='chr19:clu_42835_-', ['intron', 'itype', 'gene_name']]

                                    intron itype gene_name
10236  chr19:15397855:15398629:clu_42835_-    UP    AKAP8L
10237  chr19:15397855:15399301:clu_42835_-    PR    AKAP8L
10238  chr19:15398703:15399301:clu_42835_-    UP    AKAP8L
10239  chr19:15398766:15399301:clu_42835_-    UP    AKAP8L

In [17]:
bed_cols = list(spli.columns[:6]) + ten_tissues
spli[bed_cols]

,intron,cluster,itype,ctype,gene_name,gene_id,Brain-Anteriorcingulatecortex_BA24,Brain-Cortex,Brain-FrontalCortex_BA9,Brain-Putamen_basalganglia,Heart-AtrialAppendage,Liver,Lung,Muscle-Skeletal,Skin-NotSunExposed_Suprapubic,WholeBlood
8959,chr17:69250621:69253572:clu_39547_-,chr17:clu_39547_-,UP,"PR,UP",ABCA5,ENSG00000154265.15,0.020530,0.025151,0.021809,0.045522,0.099296,0.085712,0.272849,0.110050,0.347417,0.294201
8972,chr17:7191358:7192944:clu_38502_-,chr17:clu_38502_-,UP,"PR,UP",DLG4,ENSG00000132535.18,0.008068,0.006221,0.006589,0.011356,0.129050,0.306863,0.301347,0.066252,0.299159,0.252628
12455,chr1:19252248:19254781:clu_308_+,chr1:clu_308_+,UP,"PR,UP",MRTO4,ENSG00000053372.4,0.306945,0.322065,0.305534,0.229327,0.062910,0.014253,0.025399,0.054972,0.007988,0.009286
13848,chr1:954523:955922:clu_2407_-,chr1:clu_2407_-,UP,"PR,UP",NOC2L,ENSG00000188976.10,0.047248,0.045784,0.039061,0.057825,0.064158,0.383945,0.173702,0.041400,0.252401,0.109610
17138,chr2:96829134:96831968:clu_5250_+,chr2:clu_5250_+,UP,"PR,UP",CNNM3,ENSG00000168763.15,0.336952,0.412257,0.393379,0.336893,0.269767,0.030452,0.033893,0.474061,0.014703,0.018029
17140,chr2:96832068:96832551:clu_5250_+,chr2:clu_5250_+,UP,"PR,UP",CNNM3,ENSG00000168763.15,0.299804,0.341027,0.333069,0.294030,0.240661,0.035246,0.024083,0.383283,0.013612,0.018180
21089,chr6:166330247:166331384:clu_17021_-,chr6:clu_17021_-,UP,"PR,UP",SFT2D1,ENSG00000198818.9,0.294911,0.282679,0.346408,0.199014,0.043823,0.055749,0.043370,0.033129,0.033731,0.039604
21155,chr6:29608733:29610923:clu_16194_-,chr6:clu_16194_-,UP,"PR,UP",GABBR1,ENSG00000204681.10,0.019500,0.030233,0.016120,0.026494,0.610575,0.934454,0.954900,0.893968,0.952869,0.969060

In [18]:
spli[bed_cols]

,intron,cluster,itype,ctype,gene_name,gene_id,Brain-Anteriorcingulatecortex_BA24,Brain-Cortex,Brain-FrontalCortex_BA9,Brain-Putamen_basalganglia,Heart-AtrialAppendage,Liver,Lung,Muscle-Skeletal,Skin-NotSunExposed_Suprapubic,WholeBlood
8959,chr17:69250621:69253572:clu_39547_-,chr17:clu_39547_-,UP,"PR,UP",ABCA5,ENSG00000154265.15,0.020530,0.025151,0.021809,0.045522,0.099296,0.085712,0.272849,0.110050,0.347417,0.294201
8972,chr17:7191358:7192944:clu_38502_-,chr17:clu_38502_-,UP,"PR,UP",DLG4,ENSG00000132535.18,0.008068,0.006221,0.006589,0.011356,0.129050,0.306863,0.301347,0.066252,0.299159,0.252628
12455,chr1:19252248:19254781:clu_308_+,chr1:clu_308_+,UP,"PR,UP",MRTO4,ENSG00000053372.4,0.306945,0.322065,0.305534,0.229327,0.062910,0.014253,0.025399,0.054972,0.007988,0.009286
13848,chr1:954523:955922:clu_2407_-,chr1:clu_2407_-,UP,"PR,UP",NOC2L,ENSG00000188976.10,0.047248,0.045784,0.039061,0.057825,0.064158,0.383945,0.173702,0.041400,0.252401,0.109610
17138,chr2:96829134:96831968:clu_5250_+,chr2:clu_5250_+,UP,"PR,UP",CNNM3,ENSG00000168763.15,0.336952,0.412257,0.393379,0.336893,0.269767,0.030452,0.033893,0.474061,0.014703,0.018029
17140,chr2:96832068:96832551:clu_5250_+,chr2:clu_5250_+,UP,"PR,UP",CNNM3,ENSG00000168763.15,0.299804,0.341027,0.333069,0.294030,0.240661,0.035246,0.024083,0.383283,0.013612,0.018180
21089,chr6:166330247:166331384:clu_17021_-,chr6:clu_17021_-,UP,"PR,UP",SFT2D1,ENSG00000198818.9,0.294911,0.282679,0.346408,0.199014,0.043823,0.055749,0.043370,0.033129,0.033731,0.039604
21155,chr6:29608733:29610923:clu_16194_-,chr6:clu_16194_-,UP,"PR,UP",GABBR1,ENSG00000204681.10,0.019500,0.030233,0.016120,0.026494,0.610575,0.934454,0.954900,0.893968,0.952869,0.969060

In [19]:
ten_tissues

['Brain-Anteriorcingulatecortex_BA24',
 'Brain-Cortex',
 'Brain-FrontalCortex_BA9',
 'Brain-Putamen_basalganglia',
 'Heart-AtrialAppendage',
 'Liver',
 'Lung',
 'Muscle-Skeletal',
 'Skin-NotSunExposed_Suprapubic',
 'WholeBlood']

In [21]:
exp

Index(['chr10:clu_22970_+', 'chr10:clu_23001_+', 'chr10:clu_23004_+',
       'chr10:clu_23013_+', 'chr10:clu_23015_+', 'chr10:clu_23026_+',
       'chr10:clu_23036_+', 'chr10:clu_23082_+', 'chr10:clu_23092_+',
       'chr10:clu_23121_+',
       ...
       'chrX:clu_47808_-', 'chrX:clu_47827_-', 'chrX:clu_47833_-',
       'chrX:clu_47847_-', 'chrX:clu_47851_-', 'chrX:clu_47853_-',
       'chrX:clu_47857_-', 'chrX:clu_47863_-', 'chrX:clu_47864_-',
       'chrY:clu_47887_+'],
      dtype='object', name='cluster', length=4059)